# Generated by Django 3.2.7 on 2021-09-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210913_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_Stackoverflow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
